/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animaciones.ui;

import animaciones.ui.backend.ManejadorDeEntrada;
import animaciones.ui.backend.NumeroLinea;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author sergio
 */
public class IDE extends javax.swing.JFrame {
    NumeroLinea nl;
    ManejadorDeEntrada me;
    /**
     * Creates new form IDE
     */
    public IDE() {
        me= new ManejadorDeEntrada(this);
        initComponents();
        contarLineas();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem10 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        scrollLienzo = new javax.swing.JScrollPane();
        txtAreaLienzo = new javax.swing.JTextArea();
        scrollColor = new javax.swing.JScrollPane();
        txtAreaColor = new javax.swing.JTextArea();
        scrollPintar = new javax.swing.JScrollPane();
        txtAreaPintar = new javax.swing.JTextArea();
        scrollTiempo = new javax.swing.JScrollPane();
        txtAreaTiempo = new javax.swing.JTextArea();
        lblRuta = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        txtAreaLienzo.setColumns(20);
        txtAreaLienzo.setRows(5);
        scrollLienzo.setViewportView(txtAreaLienzo);

        jTabbedPane1.addTab("Lienzo", scrollLienzo);

        txtAreaColor.setColumns(20);
        txtAreaColor.setRows(5);
        scrollColor.setViewportView(txtAreaColor);

        jTabbedPane1.addTab("Color", scrollColor);

        txtAreaPintar.setColumns(20);
        txtAreaPintar.setRows(5);
        scrollPintar.setViewportView(txtAreaPintar);

        jTabbedPane1.addTab("Pintar", scrollPintar);

        txtAreaTiempo.setColumns(20);
        txtAreaTiempo.setRows(5);
        scrollTiempo.setViewportView(txtAreaTiempo);

        jTabbedPane1.addTab("Tiempo", scrollTiempo);

        lblRuta.setText("Ruta:");

        jMenu1.setText("Archivo");

        jMenu5.setText("Nuevo");

        jMenuItem1.setText("Lienzo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem3.setText("Color");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Tiempo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Pintar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenu1.add(jMenu5);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(menuGuardar);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Analisis");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Generar");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");

        jMenuItem8.setText("Manual Tecnico");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Manual De Usuario");
        jMenu4.add(jMenuItem9);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Acerca De");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 539, Short.MAX_VALUE)
                        .addComponent(lblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        File fileAux = null;
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.showOpenDialog(this);
        fileAux = jfc.getSelectedFile();
        if (fileAux != null) {
            NombreArchivoNuevo  nan = new NombreArchivoNuevo(this, true,2,fileAux.getPath());
            nan.setVisible(true);
            if (nan.getFile()!=null) {
                me.abrirArchivo(nan.getFile());
            }
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        File fileAux = null;
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.showOpenDialog(this);
        fileAux = jfc.getSelectedFile();
        if (fileAux != null) {
            me.abrirArchivo(fileAux);
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        me.mostrarRuta(jTabbedPane1.getSelectedIndex(), lblRuta);
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       File fileAux = null;
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.showOpenDialog(this);
        fileAux = jfc.getSelectedFile();
        if (fileAux != null) {
            NombreArchivoNuevo  nan = new NombreArchivoNuevo(this, true,0,fileAux.getPath());
            nan.setVisible(true);
            if (nan.getFile()!=null) {
                me.abrirArchivo(nan.getFile());
            }
        }
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        File fileAux = null;
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.showOpenDialog(this);
        fileAux = jfc.getSelectedFile();
        if (fileAux != null) {
            NombreArchivoNuevo  nan = new NombreArchivoNuevo(this, true,1,fileAux.getPath());
            nan.setVisible(true);
            if (nan.getFile()!=null) {
                me.abrirArchivo(nan.getFile());
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        File fileAux = null;
        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jfc.showOpenDialog(this);
        fileAux = jfc.getSelectedFile();
        if (fileAux != null) {
            NombreArchivoNuevo  nan = new NombreArchivoNuevo(this, true,3,fileAux.getPath());
            nan.setVisible(true);
            if (nan.getFile()!=null) {
                me.abrirArchivo(nan.getFile());
            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
           me.guardarFiles();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
       me.guardarFiles();
    }//GEN-LAST:event_menuGuardarActionPerformed
    private void contarLineas(){
        nl= new NumeroLinea(txtAreaLienzo);
        scrollLienzo.setRowHeaderView(nl);
        nl= new NumeroLinea(txtAreaTiempo);
        scrollTiempo.setRowHeaderView(nl);
        nl= new NumeroLinea(txtAreaColor);
        scrollColor.setRowHeaderView(nl);
        nl= new NumeroLinea(txtAreaPintar);
        scrollPintar.setRowHeaderView(nl);    
    }
    public void moverTab(int index){
        jTabbedPane1.setSelectedIndex(index);
        me.mostrarRuta(jTabbedPane1.getSelectedIndex(), lblRuta);
    }
    /**
     * @param nombreArchivo
     * @param texto 
     */

    public void setTxtAreaColor(String nombreArchivo,String texto) {
        txtAreaColor.setText(texto);
        jTabbedPane1.setTitleAt(1, nombreArchivo);
    }

    public void setTxtAreaPintar(String nombreArchivo,String texto) {
        txtAreaPintar.setText(texto);
        jTabbedPane1.setTitleAt(3, nombreArchivo);
    }
    public void setTxtAreaLienzo(String nombreArchivo,String texto) {
        txtAreaLienzo.setText(texto);
        jTabbedPane1.setTitleAt(0, nombreArchivo);
    }
    public void setTxtAreaTiempo(String nombreArchivo,String texto) {
        txtAreaTiempo.setText(texto);
        jTabbedPane1.setTitleAt(2, nombreArchivo);
    }
    public String obtenreTexto(int indice){
        switch (indice) {
            case 0:
                return txtAreaLienzo.getText();
            case 1:
                return txtAreaColor.getText();
            case 2:
                return txtAreaTiempo.getText();
            case 3:
                return txtAreaPintar.getText();
             default:
                 return null;
               
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JScrollPane scrollColor;
    private javax.swing.JScrollPane scrollLienzo;
    private javax.swing.JScrollPane scrollPintar;
    private javax.swing.JScrollPane scrollTiempo;
    private javax.swing.JTextArea txtAreaColor;
    private javax.swing.JTextArea txtAreaLienzo;
    private javax.swing.JTextArea txtAreaPintar;
    private javax.swing.JTextArea txtAreaTiempo;
    // End of variables declaration//GEN-END:variables
}
